sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - SOLR_VERSION=4.10.4
  - SOLR_VERSION=5.3.1
  - SOLR_VERSION=5.4.0
  - SOLR_VERSION=5.5.1

cache:
  apt: true
  pip: true
  directories:
    - $HOME/download-cache

addons:
  apt_packages:
    - default-jdk

install:
  - "pip install 'tornado>=4.0,<5'"
  - "pip install ."

script:
  - python run-tests.py
