sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

cache:
  apt: true
  pip: true
  directories:
    - $HOME/download-cache

addons:
  apt_packages:
    - default-jdk

install:
  - "pip install 'tornado>=4.0,<5'"
  - "pip install ."

script:
  - python run-tests.py
